name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release"
        required: false
        default: nightly

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  tagname:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.tag }}
    steps:
      - id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV

      - if: github.event_name == 'push'
        run: |
          TAG_NAME=${{ github.ref }}
          echo "TAG_NAME=${TAG_NAME#refs/tags/}" >> $GITHUB_ENV

      - if: env.TAG_NAME == ''
        run: echo "TAG_NAME=nightly-${{ steps.vars.outputs.sha_short }}" >> $GITHUB_ENV

      - id: tag
        run: echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

  macos:
    runs-on: macos-15
    needs: tagname
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install x86_64 target
        run: rustup update && rustup target add x86_64-apple-darwin

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build universal binary
        run: |
          MACOSX_DEPLOYMENT_TARGET="10.11" cargo build --profile release-lto --target=x86_64-apple-darwin
          MACOSX_DEPLOYMENT_TARGET="10.11" cargo build --profile release-lto --target=aarch64-apple-darwin
          lipo target/{x86_64,aarch64}-apple-darwin/release-lto/tiller \
            -create -output target/release-lto/tiller
          lipo target/{x86_64,aarch64}-apple-darwin/release-lto/tiller-proxy \
            -create -output target/release-lto/tiller-proxy

      - name: Create app bundle
        run: |
          mkdir -p target/release-lto/macos
          cp -Rp extra/macos/Lapce.app target/release-lto/macos/Tiller.app
          mkdir -p "target/release-lto/macos/Tiller.app/Contents/MacOS"
          cp target/release-lto/tiller "target/release-lto/macos/Tiller.app/Contents/MacOS/tiller"
          /usr/libexec/PlistBuddy -c "Set :CFBundleExecutable tiller" \
            "target/release-lto/macos/Tiller.app/Contents/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleName Tiller" \
            "target/release-lto/macos/Tiller.app/Contents/Info.plist"

      - name: Create DMG
        run: |
          ln -sf /Applications target/release-lto/macos/Applications
          hdiutil create target/release-lto/macos/Tiller-macos.dmg \
            -volname "Tiller" \
            -fs HFS+ \
            -srcfolder target/release-lto/macos \
            -ov -format UDZO

      - name: Gzip proxy binaries
        run: |
          gzip -c target/x86_64-apple-darwin/release-lto/tiller-proxy \
            > target/release-lto/macos/tiller-proxy-darwin-x86_64.gz
          gzip -c target/aarch64-apple-darwin/release-lto/tiller-proxy \
            > target/release-lto/macos/tiller-proxy-darwin-aarch64.gz

      - uses: actions/upload-artifact@v4
        with:
          name: tiller-macos
          path: |
            target/release-lto/macos/Tiller-macos.dmg
            target/release-lto/macos/tiller-proxy-darwin-*.gz
          retention-days: 3

  linux:
    runs-on: ubuntu-latest
    needs: tagname
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo make ubuntu-deps

      - name: Update Rust
        run: rustup update --no-self-update

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        run: cargo build --frozen --profile release-lto

      - name: Create tarball and proxy archive
        run: |
          mkdir tiller
          cp target/release-lto/tiller tiller/
          tar -zcvf tiller-linux-x86_64.tar.gz tiller/
          gzip -c target/release-lto/tiller-proxy > tiller-proxy-linux-x86_64.gz

      - uses: actions/upload-artifact@v4
        with:
          name: tiller-linux
          path: |
            tiller-linux-x86_64.tar.gz
            tiller-proxy-linux-x86_64.gz
          retention-days: 1

  windows:
    runs-on: windows-latest
    needs: tagname
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update --no-self-update

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        run: cargo build --frozen --profile release-lto

      - name: Create portable zip
        shell: pwsh
        run: Compress-Archive ./target/release-lto/tiller.exe ./Tiller-windows-portable.zip

      - name: Gzip proxy binary
        shell: pwsh
        run: |
          $file = [System.IO.File]::Open(
            (Join-Path $PWD '.\target\release-lto\tiller-proxy.exe'),
            [System.IO.FileMode]::Open
          )
          $archive = [System.IO.File]::Create(
            (Join-Path $PWD '.\tiller-proxy-windows-x86_64.gz')
          )
          $compressor = [System.IO.Compression.GZipStream]::new(
            $archive, [System.IO.Compression.CompressionMode]::Compress
          )
          $file.CopyTo($compressor)
          Start-Sleep -Seconds 10
          $compressor.close()

      - uses: actions/upload-artifact@v4
        with:
          name: tiller-windows
          path: |
            ./Tiller-windows-portable.zip
            ./tiller-proxy-windows-x86_64.gz
          retention-days: 1

  publish:
    needs: [macos, linux, windows]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV

      - if: github.event_name == 'push'
        run: |
          TAG_NAME=${{ github.ref }}
          echo "TAG_NAME=${TAG_NAME#refs/tags/}" >> $GITHUB_ENV

      - if: env.TAG_NAME == ''
        run: echo "TAG_NAME=nightly" >> $GITHUB_ENV

      - name: Set release metadata
        run: |
          if [[ "$TAG_NAME" == "nightly" ]]; then
            echo "PRERELEASE=--prerelease" >> $GITHUB_ENV
            echo "SUBJECT=Tiller development build" >> $GITHUB_ENV
          else
            echo "PRERELEASE=" >> $GITHUB_ENV
            echo "SUBJECT=Tiller $TAG_NAME" >> $GITHUB_ENV
          fi

      - name: Re-tag nightly
        if: env.TAG_NAME == 'nightly'
        run: |
          gh release delete nightly --yes || true
          git push origin :nightly || true

      - name: Publish release
        run: |
          gh release create "$TAG_NAME" $PRERELEASE \
            --title "$SUBJECT" \
            --target "$GITHUB_SHA" \
            tiller-macos/* \
            tiller-linux/* \
            tiller-windows/*
